monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 365
            path: "%kernel.logs_dir%/%kernel.environment%.all.log"
            level: info
            buffer_size: 50
        login:
            type: rotating_file
            max_files: 365
            path: "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level: info
            channels: security
            buffer_size: 50
        main_error:
            type: fingers_crossed
            action_level: error
            handler: streamed_error
            buffer_size: 50
        streamed_error:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: info
            buffer_size: 50
        main_critical:
            type: fingers_crossed
            action_level: critical
            handler: grouped_critical
        grouped_critical:
            type: group
            members:
                - streamed_critical
        streamed_critical:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level: critical
