monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                #type: stream
                type: rotating_file
                max_files: 365
                path: "%kernel.logs_dir%/%kernel.environment%.all.log"
                level: info
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: [ "!php" ] # retire les info de PHP?
                #excluded_http_codes: [404, 405]
            login:
                #type: stream
                type: rotating_file
                max_files: 365
                path: "%kernel.logs_dir%/%kernel.environment%.auth.log"
                level: info
                channels: security
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            main_error:
                type: fingers_crossed
                action_level: error
                handler: streamed_error
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            streamed_error:
                #type: stream
                type: rotating_file
                max_files: 10
                path: "%kernel.logs_dir%/%kernel.environment%.error.log"
                level: info
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            main_critical:
                type: fingers_crossed
                action_level: critical
                handler: grouped_critical
            grouped_critical:
                type: group
                members: [ streamed_critical ] #, buffered_critical]
            streamed_critical:
                #type: stream
                type: rotating_file
                max_files: 10
                path: "%kernel.logs_dir%/%kernel.environment%.critical.log"
                level: critical


#when@prod:
#    monolog:
#        handlers:
#            main:
#                type: fingers_crossed
#                action_level: error
#                handler: nested
#                excluded_http_codes: [404, 405]
#                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#            nested:
#                type: stream
#                path: php://stderr
#                level: debug
#                formatter: monolog.formatter.json
#            console:
#                type: console
#                process_psr_3_messages: false
#                channels: ["!event", "!doctrine"]
#            deprecation:
#                type: stream
#                channels: [deprecation]
#                path: "%kernel.logs_dir%/%kernel.environment%.error.log"
