translation:
    locales: ["fr"]
    symfony_profiler:
        enabled: true
    webui:
        enabled: true
    edit_in_place:
        enabled: false
        config_name: app
    auto_add_missing_translations:
        enabled: true
        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            output_format: yaml
