security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    role_hierarchy:
        ROLE_ADMIN: [ROLE_SES]
        ROLE_SES: [ROLE_USER]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\LoginFormAuthenticator
                - App\Security\LoginCasAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login


    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/demande-acces, roles: PUBLIC_ACCESS }
        - { path: ^/sso/cas, roles: PUBLIC_ACCESS }
        - { path: ^/fiche-matiere/export/[0-9]+, roles: PUBLIC_ACCESS}
        - { path: ^/parcours/mccc/export/.+\.pdf, roles: PUBLIC_ACCESS}
        - { path: ^/parcours/mccc/export-light/.+\.pdf, roles: PUBLIC_ACCESS}
        - { path: ^/parcours/.+/export-json-urca, roles: PUBLIC_ACCESS}
        - { path: ^/parcours/.+/export-json, roles: PUBLIC_ACCESS}
        - { path: ^/parcours/.+/export-xml-lheo, roles: PUBLIC_ACCESS }
        - { path: ^/parcours/.+/export-pdf, roles: PUBLIC_ACCESS }
        - { path: ^/parcours/.+/maquette_iframe, roles: PUBLIC_ACCESS }
        - { path: ^/fiche/matiere/.+/maquette_iframe, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
