twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        user_data: '@App\Classes\DataUserSession'
        product_name: 'ORéOF'
        mail_contact: 'oreof@univ-reims.fr'
        iconAdd: 'fal fa-plus-circle'
        iconEdit: 'fal fa-edit'
        iconDelete: 'fal fa-trash-alt'
        iconShow: 'fal fa-eye'
        iconDuplicate: 'fal fa-copy'
        iconBack: 'fal fa-arrow-left'
        iconValidate: 'fal fa-check'
when@test:
    twig:
        strict_variables: true
