#bin/console workflow:dump dpe | dot -Tpng -o dpe.png
framework:
  workflows:
    dpeParcours:
      type: 'workflow'
      marking_store:
        type: 'method'
        property: 'etatValidation'
      supports:
        - App\Entity\DpeParcours
      initial_marking: 'initialisation_dpe'
      places:
        initialisation_dpe:
          metadata:
            process: false
            label: 'validation.initialisation'
        autorisation_saisie:
          metadata:
            process: false
            label: 'validation.autorisation_saisie'
        en_cours_redaction:
          metadata:
            process: true
            icon: 'fa-pencil'
            label: 'en_cours_redaction.parcours'
            hasUpload: false
            isTimeline: false
            check: true
            templateCheck: '_checkParcours.html.twig'
        soumis_parcours:
          metadata:
            process: true
            icon: 'fa-memo-circle-check'
            label: 'validation.parcours_rf'
            isTimeline: false
            check: true
            templateCheck: '_checkParcours.html.twig'
        soumis_dpe_composante:
          metadata:
            process: true
            icon: 'fa-check-to-slot'
            label: 'validation.dpe'
            isTimeline: true
        refuse_rf:
          metadata:
            process: false
            label: 'validation.refuse_rf'
        refuse_dpe_composante:
          metadata:
            process: false
            label: 'validation.refuse_dpe_composante'
        soumis_conseil:
          metadata:
            process: true
            icon: 'fa-people-line'
            label: 'validation.conseil'
            isTimeline: true
            hasDate: true
            hasUpload: true
        refuse_conseil:
          metadata:
            process: false
            label: 'validation.refuse_conseil'
        refuse_central:
          metadata:
            process: false
            label: 'validation.refuse_central'
        soumis_central:
          metadata:
            process: true
            icon: 'fa-school-circle-check'
            label: 'validation.ses'
            isTimeline: false
        soumis_cfvu:
          metadata:
            process: true
            icon: 'fa-shield-check'
            label: 'soumis.cfvu'
            hasDate: true
            isTimeline: true
        refuse_definitif_cfvu:
          metadata:
            process: false
            label: 'validation.refuse_definitif_cfvu'
        valide_cfvu:
          metadata:
            process: true
            icon: 'fa-stamp'
            label: 'relecture.avant_publication'
            isTimeline: true
        valide_a_publier: # Etape de saisie de la date pour publication post CFVU
          metadata:
            process: true
            icon: 'fa-bullhorn'
            label: 'validation.publication'
            isTimeline: false
        publie:
          metadata:
            process: false
            icon: 'fa-bullhorn'
            label: 'publie'
            isTimeline: false
        soumis_conseil_reserve:
          metadata:
            process: false
            label: 'validation.soumis_conseil_reserve'
        en_cours_redaction_ss_cfvu:
          metadata:
            process: false
            icon: 'fa-paper-plane'
            isTimeline: false
            label: 'validation.en_cours_redaction_ss_cfvu'
        soumis_central_sans_cfvu:
          metadata:
            process: false
            icon: 'fa-school-circle-check'
            isTimeline: false
            label: 'validation.soumis_central_sans_cfvu'
        soumis_central_reserve_cfvu:
          metadata:
            process: false
            label: 'validation.soumis_central_reserve_cfvu'
        soumis_dpe_composante_reserve_cfvu:
          metadata:
            process: false
            label: 'validation.soumis_dpe_composante_reserve_cfvu'
        non_ouverture_ses:
          metadata:
            process: false
            label: 'validation.non_ouverture_ses'
        non_ouverture_cfvu:
          metadata:
            process: false
            label: 'validation.non_ouverture_cfvu'
        non_ouverture:
          metadata:
            process: false
            label: 'validation.non_ouverture'
      transitions:
        initialiser:
          guard: "is_granted('ROLE_ADMIN')"
          from: 'initialisation_dpe'
          to: 'autorisation_saisie'
        autoriser:
          from: 'autorisation_saisie'
          to: 'en_cours_redaction'
        valider_parcours: # Soumettre du resp de parcours vers formation
          from: 'en_cours_redaction'
          to: 'soumis_parcours'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        valider_rf:
          from: 'soumis_parcours'
          to: 'soumis_dpe_composante'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reserver_rf:
          from: 'soumis_parcours'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        refuser_dpe_composante:
          from: 'soumis_dpe_composante'
          to: 'refuse_dpe_composante'
          metadata:
            type: refuser
            btn: danger
            icon: fa-ban
        valider_dpe_composante:
          from: 'soumis_dpe_composante'
          to: 'soumis_conseil'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reserver_dpe_composante:
          from: 'soumis_dpe_composante'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        refuser_conseil:
          from: 'soumis_conseil'
          to: 'refuse_conseil'
          metadata:
            type: refuser
            btn: danger
            icon: fa-ban
        valider_conseil:
          from: 'soumis_conseil'
          to: 'soumis_central'
          metadata:
            type: valider
            btn: success
            hasDate: true
            hasUpload: true
            icon: fa-check
        reserver_conseil:
          from: 'soumis_conseil'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        refuser_central:
          from: 'soumis_central'
          to: 'refuse_central'
          metadata:
            type: refuser
            btn: danger
            icon: fa-ban
        valider_central:
          from: 'soumis_central'
          to: 'soumis_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reserver_central:
          from: 'soumis_central'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_publication_directe:
          from: 'soumis_central'
          to: 'valide_a_publier'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasValidLheo: true
        refuser_definitif_cfvu:
          from: 'soumis_cfvu'
          to: 'refuse_definitif_cfvu'
          metadata:
            type: refuser
            btn: danger
            icon: fa-ban
        refuser_revoir_cfvu:
          from: 'soumis_cfvu'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_reserve_cfvu:
          from: 'soumis_cfvu'
          to: 'soumis_dpe_composante_reserve_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            display: false
        transmetre_reserve_cfvu:
          from: 'soumis_dpe_composante_reserve_cfvu'
          to: 'soumis_central_reserve_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        valider_reserve_conseil_cfvu:
          from: 'soumis_cfvu'
          to: 'soumis_conseil_reserve' #todo mais on court-circuite le retour directement vers valider publicatio
          metadata:
            type: valider
            btn: success
            icon: fa-check
            display: false
        valider_reserve_central_cfvu:
          from: 'soumis_conseil_reserve'
          to: 'valide_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        valider_cfvu:
          from: 'soumis_cfvu'
          to: 'valide_cfvu' #todo: renommer en valide_cfvu => etait valide_pour_publication
          metadata:
            type: valider
            btn: success
            hasDate: true
            icon: fa-check
        valider_publication:
          from: 'valide_cfvu' #todo: renommer en valide_cfvu etait valide_pour_publication
          to: 'valide_a_publier'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasDate: true
            hasValidLheo: true
        publier:
          from: 'valide_a_publier'
          to: 'publie'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reouvrir_mccc:
          from: 'publie'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        reouvrir_sans_cfvu:
          from: 'publie'
          to: 'en_cours_redaction_ss_cfvu'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_ouverture_sans_cfvu:
          from: 'en_cours_redaction_ss_cfvu'
          to: 'soumis_central_sans_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        valider_transmettre_ouverture_sans_cfvu:
          from: 'soumis_central_sans_cfvu'
          to: 'valide_a_publier'
          metadata:
            type: valider
            btn: success
            hasDate: true
            hasValidLheo: true
            icon: fa-check
        reserver_transmettre_ouverture_sans_cfvu:
          from: 'soumis_central_sans_cfvu'
          to: 'en_cours_redaction_ss_cfvu'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_transmettre_reserve_cfvu:
          from: 'soumis_central_reserve_cfvu'
          to: 'valide_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reserver_transmettre_reserve_cfvu:
          from: 'soumis_central_reserve_cfvu'
          to: 'soumis_dpe_composante_reserve_cfvu'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_non_ouverture_ses:
          from: 'non_ouverture_ses'
          to: 'non_ouverture_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        valider_non_ouverture_cfvu:
          from: 'non_ouverture_cfvu'
          to: 'non_ouverture'
          metadata:
            type: valider
            btn: success
            icon: fa-check
    composante: # todo: Deprecated pas utilisé ?
      type: 'workflow'
      marking_store:
        type: 'method'
        property: 'etatComposante'
      supports:
        - App\Entity\Composante
      initial_marking: 'initialisation_composante'
      places:
        - 'initialisation_composante'
        - 'en_cours_redaction'
        - 'soumis_ses'
        - 'refuse_dpe'
      transitions:
        initialiser:
          guard: "is_granted('ROLE_RESP_DPE')"
          from: 'initialisation_composante'
          to: 'en_cours_redaction'
        valider_resp_dpe:
          from: 'en_cours_redaction'
          to: 'soumis_ses'
        refuser_resp_dpe:
          from: 'en_cours_redaction'
          to: 'refuse_dpe'
    fiche:
      type: 'workflow'
      marking_store:
        type: 'method'
        property: 'etatFiche'
      supports:
        - App\Entity\FicheMatiere
      initial_marking: 'en_cours_redaction'
      places:
        'en_cours_redaction':
          metadata:
            process: true
            icon: 'fa-ballot-check'
            label: 'validation.fiche_matiere'
            hasValid: true
            hasReserve: false
            hasRefuse: false
            hasUpload: false
            isTimeline: false
            hasDate: false
            transition: 'en_cours_redaction'
            canValide: 'valider_fiche_compo'
            check: true
        'soumis_central':
          metadata:
            process: true
            icon: 'fa-school-circle-check'
            label: 'validation.fiche_matiere.ses'
            hasValid: true
            hasReserve: true
            hasRefuse: true
            hasUpload: false
            isTimeline: false
            hasDate: false
            transition: 'transmis_ses'
            canValide: 'valider_fiche_ses'
            canRefuse: 'refuser_fiche_ses'
            canReserve: 'reserver_fiche_ses'
        'valide_pour_publication':
          metadata:
            process: true
            icon: 'fa-stamp'
            label: 'validation.fiche_matiere.publication'
            hasValid: false
            hasReserve: false
            hasRefuse: false
            hasUpload: false
            isTimeline: true
            hasDate: false
            transition: 'transmis_pour_publication'
            canValide: 'valider_fiche_pour_publication'
        'publie':
          metadata:
            process: false
            showOn: false
            icon: 'fa-pencil'
            label: 'fiche_matiere.rouvrir_fiche_matiere'
            hasValid: false
            hasReserve: false
            hasRefuse: false
            hasUpload: false
            isTimeline: false
            hasDate: false
            transition: 'publie'
            canValide: ''
      transitions:
        valider_fiche_compo:
          from: 'en_cours_redaction'
          to: 'soumis_central'
          metadata:
            type: valider
            btn: success
            icon: 'fa-ballot-check'
        valider_fiche_ses:
          from: 'soumis_central'
          to: 'valide_pour_publication'
          metadata:
            type: valider
            btn: success
            icon: 'fa-stamp'
        reserver_fiche_ses:
          from: 'soumis_central'
          to: 'en_cours_redaction'
          metadata:
            type: reserver
            btn: warning
            icon: fa-check
        publier:
          from: 'valide_pour_publication'
          to: 'publie'
          metadata:
        rouvrir_fiche_matiere:
          from: 'publie'
          to: 'en_cours_redaction'
          metadata:
            type: valider
            btn: warning
            icon: 'fa-pencil'
        rouvrir_fiche_matiere_b:
          from: 'soumis_central'
          to: 'en_cours_redaction'
          metadata:
            type: valider
            btn: warning
            icon: 'fa-pencil'
    changeRf:
      type: 'workflow'
      marking_store:
        type: 'method'
        property: 'etatDemande'
      supports:
        - App\Entity\ChangeRf
      initial_marking: 'demande_initialisee'
      places:
        demande_initialisee:
          metadata:
            process: false
        soumis_conseil:
          metadata:
            process: true
            icon: 'fa-people-line'
            label: 'validation.soumis_conseil'
        soumis_ses:
          metadata:
            process: true
            icon: 'fa-school-circle-check'
            label: 'validation.soumis_ses'
        soumis_cfvu:
          metadata:
            process: true
            icon: 'fa-shield-check'
            label: 'validation.soumis_cfvu'
        attente_pv:
          metadata:
            process: false
        effectuee:
          metadata:
            process: false
        verification_pv:
          metadata:
            process: false
      transitions:
        effectuer_demande:
          from: 'demande_initialisee'
          to: 'soumis_conseil'
        valider_conseil:
          from: 'soumis_conseil'
          to: 'soumis_ses'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasDate: true
            hasUpload: true
        valider_ses:
          from: 'soumis_ses'
          to: 'soumis_cfvu'
          metadata:
            type: valider
            btn: success
            icon: fa-check
        reserver_ses:
          from: 'soumis_ses'
          to: 'demande_initialisee'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        valider_cfvu_avec_pv:
          from: 'soumis_cfvu'
          to: 'effectuee'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasDate: true
        valider_cfvu_attente_pv:
          from: 'soumis_cfvu'
          to: 'attente_pv'
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasDate: true
        reserver_cfvu:
          from: 'soumis_cfvu'
          to: 'demande_initialisee'
          metadata:
            type: reserver
            btn: warning
            icon: fa-circle-exclamation-check
        deposer_pv:
          from: 'attente_pv'
          to: 'verification_pv' #etape intermédiaire de contrôle
          metadata:
            type: valider
            btn: success
            icon: fa-check
            hasUpload: true
        valider_pv:
          from: 'verification_pv'
          to: 'effectuee'
          metadata:
            type: valider
            btn: success
            icon: fa-check
