#bin/console workflow:dump parcours | dot -Tpng -o graph.png
framework:
    workflows:
        dpe:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'etatDpe'
            supports:
                - App\Entity\Formation
            initial_marking: 'initialisation_dpe'
            places:
                - 'initialisation_dpe'
                - 'autorisation_saisie'
                - 'en_cours_redaction'
                - 'soumis_rf'
                - 'soumis_dpe_composante'
                - 'refuse_rf'
                - 'refuse_dpe_composante'
                - 'soumis_conseil'
                - 'refuse_conseil'
                - 'refuse_central'
                - 'soumis_central'
                - 'soumis_vp'
                - 'soumis_cfvu'
                - 'refuse_definitif_cfvu'
                - 'valide_a_publier'
                - 'publie'
                - 'valide_pour_publication'
                - 'soumis_conseil_reserve'
            transitions:
                initialiser:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: 'initialisation_dpe'
                    to: 'autorisation_saisie' #evoi mail aux responsable de formation et aux responsable DPE
                autoriser:
                    from: 'autorisation_saisie'
                    to: 'en_cours_redaction' # dès qu'un champs est modifié
                valide_rf:
                    from: 'en_cours_redaction'
                    to: 'soumis_dpe_composante'
                reserver_rf:
                    from: 'soumis_rf'
                    to: 'en_cours_redaction'
                refuser_dpe_composante:
                    from: 'soumis_dpe_composante'
                    to: 'refuse_dpe_composante'
                valide_dpe_composante:
                    from: 'soumis_dpe_composante'
                    to: 'soumis_conseil'
                reserver_dpe_composante:
                    from: 'soumis_dpe_composante'
                    to: 'en_cours_redaction'
                refuser_conseil:
                    from: 'soumis_conseil'
                    to: 'refuse_conseil'
                valider_conseil:
                    from: 'soumis_conseil'
                    to: 'soumis_central'
                reserver_conseil:
                    from: 'soumis_conseil'
                    to: 'en_cours_redaction'
                laisser_passer_conseil:
                    from: 'soumis_conseil'
                    to: 'soumis_central'
                refuser_central:
                    from: 'soumis_central'
                    to: 'refuse_central'
                valider_central:
                    from: 'soumis_central'
                    to: 'soumis_vp'
                reserver_central:
                    from: 'soumis_central'
                    to: 'en_cours_redaction'
                transmettre_cfvu:
                    from: 'soumis_vp'
                    to: 'soumis_cfvu'
                refuser_definitif_cfvu:
                    from: 'soumis_cfvu'
                    to: 'refuse_definitif_cfvu'
                refuser_revoir_cfvu:
                    from: 'soumis_cfvu'
                    to: 'en_cours_redaction'
                valider_reserve_cfvu:
                    from: 'soumis_cfvu'
                    to: 'en_cours_redaction'
                valider_reserve_conseil_cfvu:
                    from: 'soumis_cfvu'
                    to: 'soumis_conseil_reserve' #todo mais on court-circuite le retour directement vers valider publicatio
                valider_reserve_central_cfvu:
                    from: 'soumis_conseil_reserve'
                    to: 'valide_pour_publication'
                valider_cfvu:
                    from: 'soumis_cfvu'
                    to: 'valide_pour_publication'
                valider_publication:
                    from: 'valide_pour_publication'
                    to: 'valide_a_publier'
                publier:
                    from: 'valide_a_publier'
                    to: 'publie'
        parcours:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'etatParcours'
            supports:
                - App\Entity\Parcours
            initial_marking: 'initialisation_parcours'
            places:
                - 'initialisation_parcours'
                - 'autorisation_saisie'
                - 'en_cours_redaction'
                - 'soumis_parcours'
                #- 'reserve_parcours_rf'
                - 'valide_parcours_rf'
            transitions:
                initialiser:
                    from: 'initialisation_parcours'
                    to: 'autorisation_saisie'
                autoriser:
                    from: 'autorisation_saisie'
                    to: 'en_cours_redaction'
                valider_parcours: # Soumettre du resp de parcours vers formation
                    from: 'en_cours_redaction'
                    to: 'soumis_parcours'
                reserver_rf:
                    from: 'soumis_parcours'
                    to: 'en_cours_redaction'
                valider_rf:
                    from: 'soumis_parcours'
                    to: 'valide_parcours_rf'
        composante:
            type: 'workflow'
            marking_store:
                type: 'method'
                property: 'etatComposante'
            supports:
                - App\Entity\Composante
            initial_marking: 'initialisation_composante'
            places:
                - 'initialisation_composante'
                - 'en_cours_redaction'
                - 'soumis_ses'
                - 'refuse_dpe'
            transitions:
                initialiser:
                    guard: "is_granted('ROLE_RESP_DPE')"
                    from: 'initialisation_composante'
                    to: 'en_cours_redaction'
                valider_resp_dpe:
                    from: 'en_cours_redaction'
                    to: 'soumis_ses'
                refuser_resp_dpe:
                    from: 'en_cours_redaction'
                    to: 'refuse_dpe'
