npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "034AD4AE-60AC-4209-AB6C-89F666D5BE1E"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "034AD4AE-60AC-4209-AB6C-89F666D5BE1E"
