process:
  fiche_matiere:
    icon: 'fa-ballot-check'
    label: 'validation.fiche_matiere'
    isTimeline: false
    transition: 'en_cours_redaction'
    check: true
  parcours:
    icon: 'fa-paper-plane'
    label: 'validation.parcours'
    isTimeline: false
    transition: 'en_cours_redaction'
    check: true
  formation:
    icon: 'fa-file-circle-check'
    label: 'validation.formation'
    isTimeline: false
    transition: 'en_cours_redaction'
    check: true
  dpe:
    icon: 'fa-check-to-slot'
    label: 'validation.dpe'
    isTimeline: true
    showOn: false
    transition: 'soumis_dpe_composante'
  conseil:
    icon: 'fa-people-line'
    label: 'validation.conseil'
    isTimeline: true
    showOn: false
    transition: 'soumis_conseil'
  change_rf:
    icon: 'fa-person-chalkboard'
    label: 'validation.change_rf'
    isTimeline: false
    transition: 'soumis_cfvu'
  cfvu:
    icon: 'fa-stamp'
    label: 'validation.cfvu'
    isTimeline: true
    showOn: false
    transition: 'soumis_cfvu'
  publication:
    icon: 'fa-bullhorn'
    label: 'validation.publication'
    isTimeline: true
    transition: 'valide_pour_publication'
